spring.datasource.url=jdbc:mysql://localhost:3306/careerai_db
spring.datasource.username=root
spring.datasource.password=CareerAI@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

groq.api.key=dummy-api-key